# Generated by Django 4.0.4 on 2022-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Prompt')),
                ('psid', models.IntegerField(verbose_name='psID')),
            ],
            options={
                'verbose_name': 'GptBot',
                'verbose_name_plural': 'GptBots',
            },
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Hospital Name'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ambulances', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
