# Generated by Django 4.0.4 on 2022-05-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gptbot_alter_ambulance_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone No.'),
        ),
    ]
