# Generated by Django 4.0.4 on 2022-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ambulance_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterRelif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'DisasterRelif',
                'verbose_name_plural': 'DisasterRelifs',
            },
        ),
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Violence',
                'verbose_name_plural': 'Violences',
            },
        ),
    ]
