# Generated by Django 4.0.4 on 2022-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_disasterrelif_violence'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptbot',
            name='is_address',
            field=models.BooleanField(default=False, verbose_name='is_address'),
        ),
        migrations.AddField(
            model_name='gptbot',
            name='service_id',
            field=models.IntegerField(default=0, verbose_name='service_id'),
        ),
    ]
